'use client';

import { useState } from 'react';

export default function DigestPage() {
  const [activeTab, setActiveTab] = useState<'daily' | 'weekly'>('daily');

  return (
    <div className="mx-auto max-w-lg px-5 pt-8">
      {/* Header */}
      <header className="mb-8 animate-fade-up">
        <div className="flex items-center gap-3 mb-2">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-[var(--accent-cyan)] to-blue-600 text-lg">
            📊
          </div>
          <h1 className="text-3xl font-bold tracking-tight text-[var(--text-primary)]">
            Digest
          </h1>
        </div>
        <p className="text-base text-[var(--text-muted)] ml-[52px]">
          AI-generated summaries
        </p>
      </header>

      {/* Tabs */}
      <div className="mb-6 flex gap-2 animate-fade-up delay-1" style={{ opacity: 0 }}>
        <button
          onClick={() => setActiveTab('daily')}
          className={`flex-1 rounded-xl py-3 text-sm font-medium transition-all ${
            activeTab === 'daily'
              ? 'bg-[var(--accent-cyan)] text-[var(--bg-deep)]'
              : 'bg-[var(--bg-elevated)] text-[var(--text-secondary)] hover:bg-[var(--bg-surface)]'
          }`}
        >
          Daily Briefing
        </button>
        <button
          onClick={() => setActiveTab('weekly')}
          className={`flex-1 rounded-xl py-3 text-sm font-medium transition-all ${
            activeTab === 'weekly'
              ? 'bg-[var(--accent-cyan)] text-[var(--bg-deep)]'
              : 'bg-[var(--bg-elevated)] text-[var(--text-secondary)] hover:bg-[var(--bg-surface)]'
          }`}
        >
          Weekly Review
        </button>
      </div>

      {/* Content */}
      <div className="animate-fade-up delay-2" style={{ opacity: 0 }}>
        {activeTab === 'daily' ? (
          <div className="glass-card p-6">
            <div className="flex items-center gap-3 mb-4">
              <span className="text-2xl">☀️</span>
              <div>
                <h2 className="text-lg font-semibold text-[var(--text-primary)]">Daily Briefing</h2>
                <p className="text-xs text-[var(--text-muted)]">
                  {new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}
                </p>
              </div>
            </div>

            <div className="space-y-4">
              <div className="rounded-xl bg-[var(--bg-elevated)] p-4">
                <h3 className="text-sm font-medium text-[var(--text-primary)] mb-2">
                  🎯 Today's Focus
                </h3>
                <p className="text-sm text-[var(--text-secondary)]">
                  Your daily digest will appear here when generated by the n8n workflow.
                </p>
              </div>

              <div className="rounded-xl bg-[var(--bg-elevated)] p-4">
                <h3 className="text-sm font-medium text-[var(--text-primary)] mb-2">
                  📋 Active Tasks
                </h3>
                <p className="text-sm text-[var(--text-secondary)]">
                  Pending Admin items and active Projects will be summarized here.
                </p>
              </div>

              <div className="rounded-xl bg-[var(--bg-elevated)] p-4">
                <h3 className="text-sm font-medium text-[var(--text-primary)] mb-2">
                  👥 Follow-ups Due
                </h3>
                <p className="text-sm text-[var(--text-secondary)]">
                  People entries with follow-up dates will appear here.
                </p>
              </div>
            </div>

            <p className="mt-4 text-center text-xs text-[var(--text-muted)]">
              Digest generated daily at 6:30 AM
            </p>
          </div>
        ) : (
          <div className="glass-card p-6">
            <div className="flex items-center gap-3 mb-4">
              <span className="text-2xl">📅</span>
              <div>
                <h2 className="text-lg font-semibold text-[var(--text-primary)]">Weekly Review</h2>
                <p className="text-xs text-[var(--text-muted)]">
                  Week of {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric' })}
                </p>
              </div>
            </div>

            <div className="space-y-4">
              <div className="rounded-xl bg-[var(--bg-elevated)] p-4">
                <h3 className="text-sm font-medium text-[var(--text-primary)] mb-2">
                  ✅ Completed This Week
                </h3>
                <p className="text-sm text-[var(--text-secondary)]">
                  Tasks marked Done and Projects marked Complete will be listed here.
                </p>
              </div>

              <div className="rounded-xl bg-[var(--bg-elevated)] p-4">
                <h3 className="text-sm font-medium text-[var(--text-primary)] mb-2">
                  💡 New Ideas
                </h3>
                <p className="text-sm text-[var(--text-secondary)]">
                  Ideas captured this week will be summarized here.
                </p>
              </div>

              <div className="rounded-xl bg-[var(--bg-elevated)] p-4">
                <h3 className="text-sm font-medium text-[var(--text-primary)] mb-2">
                  📈 Patterns & Insights
                </h3>
                <p className="text-sm text-[var(--text-secondary)]">
                  AI-identified themes and patterns from your captures.
                </p>
              </div>
            </div>

            <p className="mt-4 text-center text-xs text-[var(--text-muted)]">
              Weekly review generated every Sunday at 3:00 PM
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
